using System.Collections.Generic;
using Asu.Utilidades.Constantes;

namespace Asu.Utilidades.Clases.ArchivoASS {
    /// <summary>
    /// Representa la sección [ScryptInfo] de un archivo ASS.
    /// </summary>
    public class ScriptInfo {
        /// <summary>
        /// Obtiene o establece la lista de comentarios.
        /// </summary>
        public List<string> Comments { get; set; }

        /// <summary>
        /// Obtiene o establece el título del script.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// Obtiene o establece el tipo del script.
        /// </summary>
        public string ScriptType { get; set; }

        /// <summary>
        /// Obtiene o establece el estilo de ajuste de línea.
        /// </summary>
        public WrapStyles WrapStyle { get; set; }

        /// <summary>
        /// Obtiene o establece la resolución horizontal.
        /// </summary>
        public int PlayResX { get; set; }

        /// <summary>
        /// Obtiene o establece la resolución vertical.
        /// </summary>
        public int PlayResY { get; set; }

        /// <summary>
        /// Indica si la propiedad "Escalar borde y sombra" está activada.
        /// </summary>
        public bool ScaledBorderAndShadow { get; set; }

        /// <summary>
        /// Obtiene o establece la matriz YCbCr.
        /// </summary>
        public YCbCrMatrices YCbCrMatrix { get; set; }

        /// <summary>
        /// Obtiene o establece la lista con otras propiedades desconocidas.
        /// </summary>
        public List<string> Others { get; set; }

        /// <summary>
        /// Inicializa una nueva instancia de la clase <see cref="ScriptInfo"/>.
        /// </summary>
        public ScriptInfo() {
            Comments = new List<string>();
            Title = "";
            ScriptType = "";
            WrapStyle = WrapStyles.AjusteDeFinDeLinea;
            PlayResX = 1280;
            PlayResY = 720;
            ScaledBorderAndShadow = true;
            YCbCrMatrix = YCbCrMatrices.None;
            Others = new List<string>();
        }

        /// <summary>
        /// Inicializa una nueva instancia de la clase <see cref="ScriptInfo"/>, copiando las propiedades de otra instancia.
        /// </summary>
        /// <param name="scriptInfo"></param>
        public ScriptInfo(ScriptInfo scriptInfo) {
            Comments = scriptInfo.Comments;
            Title = scriptInfo.Title;
            ScriptType = scriptInfo.ScriptType;
            WrapStyle = scriptInfo.WrapStyle;
            PlayResX = scriptInfo.PlayResX;
            PlayResY = scriptInfo.PlayResY;
            ScaledBorderAndShadow = scriptInfo.ScaledBorderAndShadow;
            YCbCrMatrix = scriptInfo.YCbCrMatrix;
            Others = scriptInfo.Others;
        }

        /// <summary>
        /// Establece los valores por defecto usados por Aegisub para un script.
        /// </summary>
        public void SetDefaultValues() {
            Comments = new List<string>() {
                "Script generated by Aegisub 3.2.2",
                "http://www.aegisub.org/"
            };
            Title = "Default Aegisub file";
            ScriptType = "v4.00+";
            WrapStyle = WrapStyles.AjusteDeFinDeLinea;
            PlayResX = 1280;
            PlayResY = 720;
            ScaledBorderAndShadow = true;
            YCbCrMatrix = YCbCrMatrices.None;
            Others = new List<string>();
        }

        /// <summary>
        /// Devuelve una cadena con toda la sección.
        /// </summary>
        public override string ToString() {
            var _Comments = "";
            var _WrapStyle = (int) WrapStyle;
            var _ScaledBorderAndShadow = "no";
            var _YCbCrMatrix = YCbCrMatricesInfo.YCbCrMatrixToString(YCbCrMatrix);
            var _Others = "";

            Comments.ForEach(c => {
                _Comments += "\n; " + c;
            });

            Others.ForEach(x => {
                _Others += "\n" + x;
            });

            if (ScaledBorderAndShadow) {
                _ScaledBorderAndShadow = "yes";
            }

            return string.Format("[Script Info]{0}\nTitle: {1}\nScriptType: {2}\nWrapStyle: {3}\nScaledBorderAndShadow: {4}\nPlayResX: {5}\nPlayResY: {6}\nYCbCr Matrix: {7}{8}", _Comments, Title, ScriptType, _WrapStyle, _ScaledBorderAndShadow, PlayResX, PlayResY, _YCbCrMatrix, _Others);
        }
    }
}
