namespace Asu.Utilidades.Constantes {
    /// <summary>
    /// Especifica tags del formato ASS documentados en Aegisub.
    /// </summary>
    public enum Tags {
        I,
        B,
        U,
        S,
        Bord,
        BordX,
        BordY,
        Shad,
        ShadX,
        ShadY,
        Be,
        Blur,
        Fn,
        Fs,
        Fscx,
        Fscy,
        Fsp,
        Frz,
        Frx,
        Fry,
        Fax,
        Fay,
        Fe,
        Color1,
        Color2,
        Color3,
        Color4,
        Alpha,
        Alpha1,
        Alpha2,
        Alpha3,
        Alpha4,
        A,
        An,
        K,
        Kf,
        Ko,
        Q,
        Fx,
        R,
        Pos,
        Move,
        Org,
        Fade,
        Fad,
        T,
        ClipI,
        Clip,
        P,
        Pbo
    }
}
